apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  labels:
    app: postresql
    label: postgresql-service
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector: 
    app: postgresql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-deployment
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
      label: postgresql-service
  template:
    metadata:
      labels:
        app: postgresql
        label: postgresql-service
    spec:
      containers:
      - name: postgresql
        image: postgres:10-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "test"
        - name: POSTGRES_PASSWORD
          value: "test"