version: '3.4'

x-logging:
  &logging
  driver: gelf
  options:
    gelf-address: udp://${GELF_IP}:${GELF_PORT}

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    environment:
      - node.name=es-test
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node # uses only for test clusters
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    #  - networks.host=10.5.0.6
    #  - http.port=9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    logging: *logging
    volumes:
      - data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  data: