version: '3.4'

x-logging:
  &logging
  driver: gelf
  options:
    gelf-address: udp://${GELF_IP}:${GELF_PORT}

services:
  mariadb:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: perfkit_db_ci
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    logging: *logging
    ports:
      - "3306:3306"

volumes:
  mariadb:
