version: '3.4'

x-logging:
  &logging
  driver: gelf
  options:
    gelf-address: udp://${GELF_IP}:${GELF_PORT}

services:
  cassandra:
    image: cassandra:4.0
    environment:
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=password # example value of a secret
    volumes:
      - cassandra-data:/var/lib/cassandra
    logging: *logging
    ports:
      - "9042:9042"

  init:
    image: cassandra:4.0
    depends_on:
      - cassandra
    restart: "no"
    entrypoint: ["/init.sh"]
    volumes:
      - ./init.sh:/init.sh

volumes:
  cassandra-data:
