version: '3.4'

x-logging:
  &logging
  driver: gelf
  options:
    gelf-address: udp://${GELF_IP}:${GELF_PORT}

services:
  pgvector:
    image: ankane/pgvector:v0.5.1
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: perfkit_pg_vector_db_ci
    logging: *logging
    ports:
      - "5432:5432"

volumes:
  pgvector:
